// Code generated by SQLBoiler 4.3.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Analyzes          string
	Doctor            string
	Patient           string
	Reception         string
	Reviews           string
	SpecializationKit string
	Specializations   string
	Timetable         string
}{
	Analyzes:          "analyzes",
	Doctor:            "doctor",
	Patient:           "patient",
	Reception:         "reception",
	Reviews:           "reviews",
	SpecializationKit: "specialization_kit",
	Specializations:   "specializations",
	Timetable:         "timetable",
}
