// Code generated by SQLBoiler 4.3.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Analyzes", testAnalyzesUpsert)

	t.Run("Doctors", testDoctorsUpsert)

	t.Run("Patients", testPatientsUpsert)

	t.Run("Receptions", testReceptionsUpsert)

	t.Run("Reviews", testReviewsUpsert)

	t.Run("SpecializationKits", testSpecializationKitsUpsert)

	t.Run("Specializations", testSpecializationsUpsert)

	t.Run("Timetables", testTimetablesUpsert)
}
