// Code generated by SQLBoiler 4.3.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testReviews(t *testing.T) {
	t.Parallel()

	query := Reviews()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testReviewsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Reviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testReviewsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Reviews().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Reviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testReviewsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ReviewSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Reviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testReviewsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ReviewExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Review exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ReviewExists to return true, but got false.")
	}
}

func testReviewsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	reviewFound, err := FindReview(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if reviewFound == nil {
		t.Error("want a record, got nil")
	}
}

func testReviewsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Reviews().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testReviewsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Reviews().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testReviewsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	reviewOne := &Review{}
	reviewTwo := &Review{}
	if err = randomize.Struct(seed, reviewOne, reviewDBTypes, false, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}
	if err = randomize.Struct(seed, reviewTwo, reviewDBTypes, false, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = reviewOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = reviewTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Reviews().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testReviewsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	reviewOne := &Review{}
	reviewTwo := &Review{}
	if err = randomize.Struct(seed, reviewOne, reviewDBTypes, false, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}
	if err = randomize.Struct(seed, reviewTwo, reviewDBTypes, false, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = reviewOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = reviewTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Reviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func reviewBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Review) error {
	*o = Review{}
	return nil
}

func reviewAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Review) error {
	*o = Review{}
	return nil
}

func reviewAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Review) error {
	*o = Review{}
	return nil
}

func reviewBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Review) error {
	*o = Review{}
	return nil
}

func reviewAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Review) error {
	*o = Review{}
	return nil
}

func reviewBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Review) error {
	*o = Review{}
	return nil
}

func reviewAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Review) error {
	*o = Review{}
	return nil
}

func reviewBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Review) error {
	*o = Review{}
	return nil
}

func reviewAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Review) error {
	*o = Review{}
	return nil
}

func testReviewsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Review{}
	o := &Review{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, reviewDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Review object: %s", err)
	}

	AddReviewHook(boil.BeforeInsertHook, reviewBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	reviewBeforeInsertHooks = []ReviewHook{}

	AddReviewHook(boil.AfterInsertHook, reviewAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	reviewAfterInsertHooks = []ReviewHook{}

	AddReviewHook(boil.AfterSelectHook, reviewAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	reviewAfterSelectHooks = []ReviewHook{}

	AddReviewHook(boil.BeforeUpdateHook, reviewBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	reviewBeforeUpdateHooks = []ReviewHook{}

	AddReviewHook(boil.AfterUpdateHook, reviewAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	reviewAfterUpdateHooks = []ReviewHook{}

	AddReviewHook(boil.BeforeDeleteHook, reviewBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	reviewBeforeDeleteHooks = []ReviewHook{}

	AddReviewHook(boil.AfterDeleteHook, reviewAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	reviewAfterDeleteHooks = []ReviewHook{}

	AddReviewHook(boil.BeforeUpsertHook, reviewBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	reviewBeforeUpsertHooks = []ReviewHook{}

	AddReviewHook(boil.AfterUpsertHook, reviewAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	reviewAfterUpsertHooks = []ReviewHook{}
}

func testReviewsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Reviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testReviewsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(reviewColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Reviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testReviewsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testReviewsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ReviewSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testReviewsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Reviews().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	reviewDBTypes = map[string]string{`ID`: `int`, `PatientID`: `int`, `DoctorID`: `int`, `Text`: `text`, `Rating`: `float`, `CreatedAt`: `timestamp`}
	_             = bytes.MinRead
)

func testReviewsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(reviewPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(reviewAllColumns) == len(reviewPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Reviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testReviewsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(reviewAllColumns) == len(reviewPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Review{}
	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Reviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, reviewDBTypes, true, reviewPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(reviewAllColumns, reviewPrimaryKeyColumns) {
		fields = reviewAllColumns
	} else {
		fields = strmangle.SetComplement(
			reviewAllColumns,
			reviewPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ReviewSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testReviewsUpsert(t *testing.T) {
	t.Parallel()

	if len(reviewAllColumns) == len(reviewPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLReviewUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Review{}
	if err = randomize.Struct(seed, &o, reviewDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Review: %s", err)
	}

	count, err := Reviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, reviewDBTypes, false, reviewPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Review struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Review: %s", err)
	}

	count, err = Reviews().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
